name: Update Recent Activity

on:
  schedule:
    - cron: '0 8 * * *' # daily at 08:00 UTC
  workflow_dispatch: {}

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Update activity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/update_activity.py --user trosinski08 --file "# 👋 Hi, I'm Tomasz Rosiński.md" --limit 5
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "# 👋 Hi, I'm Tomasz Rosiński.md"
          git commit -m "chore: update recent activity" || echo "No changes to commit"
          git push origin HEAD:main || echo "Push failed - ensure repo has main branch"

